---
# tasks file for docker
- name: create image docker
  docker_image:
    path: /var/lib/jenkins/workspace/devops
    name: devops
    tag: v1
    
- name: run container docker
  docker_container: 
    name: myapp_container
    user: root
    image: devops:latest
    state: started
    recreate: true
    ports:
     - "4200:80" 
    
